let view_p = document.getElementById('view_one');
let hide_p = document.getElementById('hide_one');
let view_o = document.getElementById('view_two');
let pieceContainer = document.getElementById('piece-container')
count = 0;
var pawn = document.getElementById('pawn');
var bishop = document.getElementById('bishop');
var rook = document.getElementById('rook');
var knight = document.getElementById('knight');
var king = document.getElementById('king');
var queen = document.getElementsByClassName('Queen');
var italian = document.getElementsByClassName('Opening')[0];
var london = document.getElementsByClassName('Opening')[1];
var english = document.getElementsByClassName('Opening')[2];
var scicilian = document.getElementsByClassName('Opening')[3];
var dutch = document.getElementsByClassName('Opening')[4];
var modern = document.getElementsByClassName('Opening')[5];
const increase = () => {count += 1;
    if(count >= 1){pawn.style.display = 'block'}else{pawn.style.display = 'none'};
    if(count >= 1){pieceContainer.style.display = 'flex'}else{pieceContainer.style.display = 'none'};
    if(count >= 1){hide_p.style.display = 'block'}else{hide_p.style.display = 'none'};
    if(count >= 2){bishop.style.display = 'block'}else{bishop.style.display = 'none'};
    if(count >= 3){rook.style.display = 'block'}else{rook.style.display = 'none'};
    if(count >= 4){knight.style.display = 'block'}else{knight.style.display = 'none'};
    if(count >= 5){king.style.display = 'block'}else{king.style.display = 'none'};
    if(count >= 6){queen.style.display = 'block'}else{queen.style.display = 'none'};
    };
const decrease = () => {count -= 1;
    if(count < 1){hide_p.style.display = 'none'};
    if(count >= 1){pawn.style.display = 'block'}else{pawn.style.display = 'none'};
    if(count >= 1){pieceContainer.style.display = 'flex'}else{pieceContainer.style.display = 'none'};
    if(count >= 2){bishop.style.display = 'block'}else{bishop.style.display = 'none'};
    if(count >= 3){rook.style.display = 'block'}else{rook.style.display = 'none'};
    if(count >= 4){knight.style.display = 'block'}else{knight.style.display = 'none'};
    if(count >= 5){king.style.display = 'block'}else{king.style.display = 'none'};
    if(count >= 6){queen.style.display = 'block'}else{queen.style.display = 'none'
};
}
view_p.addEventListener('click', increase);
hide_p.addEventListener('click', decrease);
